FROM python:3.9-slim

WORKDIR /app

RUN pip install --upgrade pip --no-cache-dir
RUN pip install gunicorn==20.1.0 --no-cache-dir

COPY requirements.txt .

RUN pip install -r requirements.txt --no-cache-dir

COPY . .

cmd ["gunicorn", "--bind", "0.0.0.0:8000", "backend.wsgi"]

